[project]
name = "dlnaPlay"
description = "Discover dlna palyer devices and cast media to play. 选择局域网的DLNA设备，播放本地音乐或视频文件，可以播放m3u歌单列表。"
readme = "README.md"
requires-python = ">=3.8,<4.0"
license = "MIT OR Apache-2.0"
authors = [
  {name = "sffzh", email = "ryan@sffzh.cn"}
]
dependencies = [ 
    "requests>=2.31.0", 
    "argparse (>=1.4.0)", 
    "twisted (>=25.5.0)", 
    ]
dynamic = ["version"]  # version 不再写死

[project.scripts] 
dlnaPlay = "dlnaPlay.main:main"

[project.urls]
Homepage = "https://github.com/sffzh/dlnaCast"
Source = "https://github.com/sffzh/dlnaCast"
Issues = "https://github.com/sffzh/dlnaCast/issues"

[build-system]
requires = ["setuptools>=64", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "src/dlnaPlay/_version.py"

[tool.poetry]
name = "dlnaPlay"
version = "0.0.0"  # 占位符，实际不会使用

[tool.poetry-dynamic-versioning]
enable = true
